#-----------------------------------------#
# Server Configuration
#-----------------------------------------#
server.port=2025

#-----------------------------------------#
# Credentials by Environment
#-----------------------------------------#
# UAT
uat.username=ApiGee@JS
uat.password=ApiGee@JS
# PROD
prod.username=ApiGee@JS
prod.password=ApiGee@JS

#-----------------------------------------#
# API URLs by Environment
#-----------------------------------------#

#-----REST-----#
# Blink Account
blinkaccount.uat.url=http://192.168.130.31:7070/js-blb-integration/ws/api/blinkaccount
blinkaccount.prod.url=http://192.168.130.31:7070/js-blb-integration/ws/api/blinkaccount

# Raast Inquiry
raastinquiry.uat.url=https://192.168.189.2:7863/casintegrationservice/api/account?aliasType=MOBILE&aliasValue=03476203879
raastinquiry.prod.url=https://192.168.189.2:7863/casintegrationservice/api/account?aliasType=MOBILE&aliasValue=03476203879

# Send SMS
smsdispatch.uat.url=https://aikgateway.bankislami.com.pk:7860/smsdispatchers/v1/SMSSend
smsdispatch.prod.url=https://aikgateway.bankislami.com.pk:7860/smsdispatchers/v1/SMSSend

# Customer Limits
customerlimits.uat.url=http://10.150.0.5:7070/js-blb-integration/ws/api/getCustomerLimits
customerlimits.prod.url=http://10.150.0.5:7070/js-blb-integration/ws/api/getCustomerLimits

# Raast Link
raastLink.uat.url=https://192.168.189.2:7863/casintegrationservice/api/customers?uidType=CNIC&uidValue=6110120070561
raastLink.prod.url=https://192.168.189.2:7863/casintegrationservice/api/customers?uidType=CNIC&uidValue=6110120070561


#-----SOAP-----#
# Verify Account
verifyaccount.uat.url=http://192.168.130.31:7070/js-blb-integration/JsBLBIntegration
verifyaccount.prod.url=http://192.168.130.31:7070/js-blb-integration/JsBLBIntegration
verifyaccount.action=http://tempuri.org/verifyAccountRequest

# MPin Login
mpinlogin.uat.url=http://192.168.130.31:7070/js-blb-integration/JsBLBIntegration
mpinlogin.prod.url=http://192.168.130.31:7070/js-blb-integration/JsBLBIntegration
mpinlogin.action=http://tempuri.org/LoginPinRequest

# Reset PIN
resetpin.uat.url=http://10.150.0.5:7070/js-blb-integration/JsBLBIntegration
resetpin.prod.url=http://10.150.0.5:7070/js-blb-integration/JsBLBIntegration
resetpin.action=http://tempuri.org/ResetPinRequest

# MPin Registration
mpinregistration.uat.url=http://10.150.0.5:7070/js-blb-integration/JsBLBIntegration
mpinregistration.prod.url=http://10.150.0.5:7070/js-blb-integration/JsBLBIntegration
mpinregistration.action=http://tempuri.org/MpinRegistrationRequest

#-----------------------------------------#
# Timeout & Logging
#-----------------------------------------#
api.timeout-ms=5000

#logging.level.com.aik.aikdigitalwrappers=DEBUG
#logging.level.org.springframework.ws.client.MessageTracing.sent=DEBUG
#logging.level.org.springframework.ws.client.MessageTracing.received=DEBUG
