spring:
  config:
    activate:
      on-profile: prod

external:
  request-timeout-ms: 5000
  default-base-url: https://prod.api.bank.com
  endpoints:
    sms-send: https://prod.api.bank.com/smsdispatchers/v1/SMSSend
    balance-inquiry: https://prod.api.bank.com/BIWS/MBTransactions/MessageBroker/BalanceInquiry
    ministatement: https://prod.api.bank.com/mbstatements/v1/ministatement
    fullstatement: https://prod.api.bank.com/mbstatements/v1/fullstatement
    internal-title-fetch: https://prod.api.bank.com/BIWS/MBTransactions/MessageBroker/InternalTitleFetch
    internal-fund-transfer: https://prod.api.bank.com/BIWS/MBTransactions/MessageBroker/Internal_Fund_Transfer
    ibft-titlefetch: https://prod.api.bank.com/BIWS/MBTransactions/MessageBroker/IBFTTitleFetch
    soap-base: https://prod.yourserver.com/soap
    verify-account-soap-action: tem:verifyAccountRequest
    login-pin-soap-action: tem:LoginPinRequest
    reset-pin-soap-action: tem:ResetPinRequest
    mpin-registration-soap-action: tem:mpinRegistrationRequest
    login-auth-soap-action: tem:ZindigiLoginAuthenticationRequest

logging:
  level:
    root: WARN
    com.aik: INFO
