spring:
  config:
    activate:
      on-profile: dev

external:
  request-timeout-ms: 8000
  default-base-url: https://192.168.189.2:7860
  endpoints:
    sms-send: https://192.168.189.2:7860/smsdispatchers/v1/SMSSend
    balance-inquiry: https://192.168.189.4:7844/BIWS/MBTransactions/MessageBroker/BalanceInquiry
    ministatement: https://192.168.189.4:7844/mbstatements/v1/ministatement
    fullstatement: https://192.168.189.4:7844/mbstatements/v1/fullstatement
    internal-title-fetch: https://192.168.189.4:7844/BIWS/MBTransactions/MessageBroker/InternalTitleFetch
    internal-fund-transfer: https://192.168.189.4:7844/BIWS/MBTransactions/MessageBroker/Internal_Fund_Transfer
    ibft-titlefetch: https://192.168.189.2:7866/BIWS/MBTransactions/MessageBroker/IBFTTitleFetch
    soap-base: https://dev.yourserver.com/soap
    blink-base: http://192.168.130.31:7070/js-blb-integration/ws/api   # ✅ add this line
    verify-account-soap-action: tem:verifyAccountRequest
    login-pin-soap-action: tem:LoginPinRequest
    reset-pin-soap-action: tem:ResetPinRequest
    mpin-registration-soap-action: tem:mpinRegistrationRequest
    login-auth-soap-action: tem:ZindigiLoginAuthenticationRequest

logging:
  level:
    com.aik: DEBUG
